<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\RecallForm;
use yii\web\Response;
use app\models\Regions;

class FormController extends Controller {
    private $sendEmail;
    function init()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $regions = Regions::getRegions();
        $this->sendEmail = $regions[Yii::$app->params['region']]['email'] ?: Yii::$app->params['adminEmail'];
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionRecall() {
        $model = new RecallForm();
        if ($model->load(Yii::$app->request->post()) and $model->validate()) {
            $model->sendEmail($this->sendEmail);
        }
        return [
            'message' => 'Ваша заявка принята. Ожидайте ответа'
        ];
    }
}